FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /work

COPY monitoring/requirements-monitoring.txt .
RUN pip install --upgrade pip && \
    pip install -r requirements-monitoring.txt

COPY monitoring/generate_drift_report.py .

CMD ["python", "generate_drift_report.py"]
